micronaut:
    application:
        name: panel
    server:
        port: 8081
        cors:
            enabled: true

hibernate:
    hbm2ddl:
        auto: 'update'

grails:
    gorm:
        multiTenancy:
            mode: DATABASE
            tenantResolverClass: 'io.micronaut.multitenancy.gorm.HttpHeaderTenantResolver'

dataSources:
    default:
        dbCreate: validate
        driverClassName: com.mysql.jdbc.Driver
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        url: jdbc:mysql://localhost:3306/cubo
        username: root
        password: root
    cubo:
        dbCreate: validate
        driverClassName: com.mysql.jdbc.Driver
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        url: jdbc:mysql://localhost:3306/cubo
        username: root
        password: root
    cubo2:
        dbCreate: validate
        driverClassName: com.mysql.jdbc.Driver
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        url: jdbc:mysql://localhost:3306/cubo2
        username: root
        password: root